services:
    dominus.back.abstract_service:
        abstract: true
        class: Dominus\BackBundle\Service\AbstractService
        arguments:
            - "@knp_paginator"

    dominus.back.service.user:
        parent: dominus.back.abstract_service
        class: Dominus\BackBundle\Service\User\UserService
        arguments:
            - "@=service('doctrine').getRepository('ModelBundle:User\User')"

