dominus_back:
    resource: "@DominusBackBundle/Resources/config/routing.yml"
    prefix:   /admin

dominus_api:
    resource: "@DominusApiBundle/Resources/config/routing.yml"
    prefix:   /api

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
