dominus_front:
    resource: "@DominusFrontBundle/Resources/config/routing.yml"
    prefix:   /

dominus_back:
    resource: "@DominusBackBundle/Resources/config/routing.yml"
    prefix:   /admin

dominus_api:
    resource: "@DominusApiBundle/Resources/config/routing.yml"
    prefix:   /api

dominus_model:
    resource: "@DominusModelBundle/Resources/config/routing.yml"
    prefix:   /


fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
