services:
    dominus.api.service.abstract_service:
        abstract: true
        class: App\Service\AbstractService
        arguments:
            - "@doctrine.orm.entity_manager"

    ## CHARACTER FOLDER
    dominus.api.service.character.hero_class:
        parent: dominus.api.service.abstract_service
        class: Domins\Service\Character\HeroClassService

    dominus.api.service.character.hero:
        parent: dominus.api.service.abstract_service
        class: Domins\Service\Character\HeroService


    ## CRAFTING FOLDER
    dominus.api.service.crafting.formula:
        parent: dominus.api.service.abstract_service
        class: Domins\Service\Crafting\FormulaService

    dominus.api.service.crafting.job:
        parent: dominus.api.service.abstract_service
        class: App\Service\Crafting\JobService

    dominus.api.service.crafting.material:
        parent: dominus.api.service.abstract_service
        class: App\Service\Crafting\MaterialService

    dominus.api.service.crafting.material_type:
        parent: dominus.api.service.abstract_service
        class: App\Service\Crafting\MaterialTypeService

    ## DOMAIN FOLDER
    dominus.api.service.domain.bonus:
        parent: dominus.api.service.abstract_service
        class: App\Service\Domain\BonusService

    dominus.api.service.domain.guild:
        parent: dominus.api.service.abstract_service
        class: App\Service\Domain\GuildService

    dominus.api.service.domain.room:
            parent: dominus.api.service.abstract_service
            class: App\Service\Domain\RoomService